name: JSON validator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install jsonschema
        run: pip install jsonschema

      - name: Validate JSONs
        run: |
          jsonschema --instance ./problems/meta.json ./problems/schema.json
          jsonschema --instance ./problems/apple.json ./problems/schema.json
          jsonschema --instance ./problems/amazon.json ./problems/schema.json
          jsonschema --instance ./problems/netflix.json ./problems/schema.json
          jsonschema --instance ./problems/google.json ./problems/schema.json
          jsonschema --instance ./problems/microsoft.json ./problems/schema.json
          jsonschema --instance ./problems/uber.json ./problems/schema.json
          jsonschema --instance ./problems/lyft.json ./problems/schema.json
          jsonschema --instance ./problems/airbnb.json ./problems/schema.json
